services:
  operadoresago-web:
    build: .
    container_name: operadoresago-web
    ports:
      - "3005:3000"
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL:-https://web.operadoresago.com}
      CONTACT_API_URL: ${CONTACT_API_URL:-http://10.10.0.49:3001/contact}
