import Link from 'next/link'
import Navbar from '@/components/navbar'
import Footer from '@/components/footer'
import { EnergiaDisclaimer, EnergiaLegalHeader } from '@/components/energia-shell'
import { createPageMetadata } from '@/lib/seo'

export const metadata = createPageMetadata({
  title: 'Política de privacidad de Energia | AGO TECH',
  description: 'Conoce cómo Energia, aplicación de AGO TECH, trata la información de cuenta, consumo, recibos y análisis.',
  path: '/energia/privacidad',
})

const sections = [
  ['1. Alcance y responsable', 'Esta política describe el tratamiento de información en Energia, una aplicación independiente desarrollada por AGO TECH para el monitoreo y análisis del consumo eléctrico. La información de soporte publicada para este producto es contacto@operadoresago.com.'],
  ['2. Información que puede tratar Energia', 'Según las funciones que utilices, Energia puede tratar datos de cuenta y perfil, incluido tu correo electrónico; ubicaciones configuradas; medidores; lecturas; información de consumo; aparatos eléctricos configurados y sus estimaciones; recibos en PDF; fotografías de medidores; información extraída de documentos; así como resultados de análisis, predicciones, alertas y recomendaciones.'],
  ['3. Para qué se utiliza', 'La información se utiliza para crear y administrar tu cuenta, registrar lecturas, organizar ubicaciones y medidores, analizar tendencias, generar predicciones y recomendaciones, procesar recibos y ayudarte a revisar tu consumo. También puede utilizarse para atender solicitudes de soporte y mantener la operación y seguridad razonable del servicio.'],
  ['4. Procesamiento automático y revisión', 'Algunas funciones utilizan procesamiento automático para extraer información de documentos o imágenes y para generar análisis. Cuando se extrae información de un recibo, tú puedes revisarla manualmente antes de confirmarla. Las predicciones, alertas y recomendaciones son orientativas y dependen de la información disponible.'],
  ['5. Infraestructura y terceros', 'Supabase se utiliza para autenticación, base de datos y almacenamiento privado. Google Cloud Vision puede utilizarse para OCR de documentos o imágenes cuando el contenido no puede obtenerse directamente. El acceso a estos servicios se configura para cumplir la función correspondiente; los archivos privados no se describen ni se tratan como archivos públicos. Las credenciales técnicas se mantienen fuera del cliente y no deben exponerse.'],
  ['6. Seguridad', 'AGO TECH aplica medidas razonables de organización, configuración y control de acceso para proteger la información. Ningún servicio conectado a internet puede garantizar riesgo cero, por lo que recomendamos mantener tus credenciales bajo control y reportar cualquier incidente por los canales de soporte.'],
  ['7. Retención y eliminación', 'La información se conserva mientras sea necesaria para prestar las funciones de Energia, mantener tu historial o atender obligaciones operativas, y puede eliminarse cuando solicites la eliminación de tu cuenta, sujeto a las excepciones descritas abajo. La eliminación de cuenta es irreversible una vez completada.'],
  ['8. Información compartida en organizaciones', 'Si una ubicación, medidor, lectura, recibo u otro dato se comparte dentro de una organización, parte de la información puede pertenecer también a otros miembros. En esos casos, la eliminación o modificación puede requerir un tratamiento distinto para no borrar información que corresponde a otras personas; puede conservarse o transferirse según la relación de la organización.'],
  ['9. Derechos y solicitudes', 'Puedes solicitar acceso, corrección o eliminación de la información asociada a tu cuenta, además de plantear dudas sobre su tratamiento. Para iniciar una solicitud, escribe a contacto@operadoresago.com indicando el correo de tu cuenta y el detalle de lo que necesitas. Podremos pedir información razonable para verificar que la solicitud corresponde a la persona titular.'],
  ['10. Cambios a esta política', 'Esta política puede actualizarse para reflejar cambios en Energia, su infraestructura o la forma de prestar sus funciones. La versión vigente se publicará en esta página.'],
]

export default function EnergiaPrivacyPage() {
  return <><Navbar /><main id="contenido-principal" tabIndex={-1} className="min-h-screen bg-slate-50 pt-18"><EnergiaLegalHeader label="Privacidad" title="Política de privacidad" description="Información clara sobre los datos que Energia puede tratar, para qué los utiliza y cómo puedes gestionar tu cuenta." /><div className="mx-auto grid max-w-7xl gap-10 px-4 py-12 sm:px-6 sm:py-16 lg:grid-cols-[1fr_300px] lg:px-8"><article className="max-w-3xl rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm sm:p-10"><p className="mb-8 text-sm font-semibold text-slate-500">Última actualización: 31 de agosto de 2026</p><div className="space-y-9">{sections.map(([title, content]) => <section key={title}><h2 className="text-xl font-black tracking-[-0.03em] text-slate-950">{title}</h2><p className="mt-3 text-sm leading-8 text-slate-600">{content}</p></section>)}</div><div className="mt-10"><EnergiaDisclaimer /></div></article><aside className="space-y-5 lg:sticky lg:top-24 lg:self-start"><div className="rounded-3xl border border-slate-200 bg-white p-6"><p className="text-xs font-black uppercase tracking-[0.16em] text-slate-400">En esta sección</p><nav className="mt-4 space-y-3 text-sm font-bold"><a href="#contenido-principal" className="block text-slate-600 hover:text-primary">Política completa</a><Link href="/energia/eliminar-cuenta" className="block text-primary hover:text-indigo-700">Solicitar eliminación de cuenta →</Link><a href="mailto:contacto@operadoresago.com" className="block text-slate-600 hover:text-primary">Contactar soporte</a></nav></div></aside></div></main><Footer /></>
}
